In [2]:
pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.20.0-py2.py3-none-any.whl (1.3 MB)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\user\anaconda3\lib\site-packages (from mlxtend) (3.5.1)
Requirement already satisfied: joblib>=0.13.2 in c:\users\user\anaconda3\lib\site-packages (from mlxtend) (1.1.0)
Requirement already satisfied: scipy>=1.2.1 in c:\users\user\anaconda3\lib\site-packages (from mlxtend) (1.7.3)
Requirement already satisfied: pandas>=0.24.2 in c:\users\user\anaconda3\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\user\anaconda3\lib\site-packages (from mlxtend) (1.0.2)
Requirement already satisfied: setuptools in c:\users\user\anaconda3\lib\site-packages (from mlxtend) (61.2.0)
Requirement already satisfied: numpy>=1.16.2 in c:\users\user\anaconda3\lib\site-packages (from mlxtend) (1.21.5)
Requirement already satisfied: cycler>=0.10 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: packaging>=20.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (21.3)
Requirement already satisfied: pillow>=6.2.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (9.0.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.25.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.4)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2021.3)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\user\anaconda3\lib\site-packages (from scikit-learn>=1.0.2->mlxtend) (2.2.0)
Installing collected packages: mlxtend
Successfully installed mlxtend-0.20.0
Note: you may need to restart the kernel to use updated packages.

In [16]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [17]:
movies = pd.read_csv('movies.csv')
movies.head(5)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [18]:
movies = movies.drop('genres', axis = 1).join(movies.genres.str.get_dummies())

In [19]:
movies

,movieId,title,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),0,0,1,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Jumanji (1995),0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,Grumpier Old Men (1995),0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
3,4,Waiting to Exhale (1995),0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
4,5,Father of the Bride Part II (1995),0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9120,162672,Mohenjo Daro (2016),0,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
9121,163056,Shin Godzilla (2016),0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
9122,163949,The Beatles: Eight Days a Week - The Touring Y...,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
9123,164977,The Gay Desperado (1936),0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
9124,164979,"Women of '69, Unboxed",0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [20]:
frequent_itemset = apriori(movies.drop(['movieId','title','(no genres listed)'],axis = 1), min_support=0.001, use_colnames=True)

C:\Users\user\anaconda3\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:111: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [21]:
frequent_itemset

      support                                           itemsets
0    0.169315                                           (Action)
1    0.122411                                        (Adventure)
2    0.048986                                        (Animation)
3    0.063890                                         (Children)
4    0.363288                                           (Comedy)
..        ...                                                ...
449  0.002521                 (Thriller, Drama, Mystery, Sci-Fi)
450  0.001425   (Action, Animation, Children, Adventure, Comedy)
451  0.001534          (Drama, Action, Thriller, Crime, Mystery)
452  0.002959  (Fantasy, Animation, Children, Adventure, Comedy)
453  0.001205     (Animation, IMAX, Children, Adventure, Comedy)

[454 rows x 2 columns]

In [22]:
m1 = association_rules(frequent_itemset, metric='lift', min_threshold = 1.25)

In [23]:
m1

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Adventure),(Action),0.122411,0.169315,0.058301,0.476276,2.812955,0.037575,1.586111
1,(Action),(Adventure),0.169315,0.122411,0.058301,0.344337,2.812955,0.037575,1.338475
2,(Animation),(Action),0.048986,0.169315,0.011288,0.230425,1.360925,0.002994,1.079407
3,(Action),(Animation),0.169315,0.048986,0.011288,0.066667,1.360925,0.002994,1.018943
4,(Crime),(Action),0.120548,0.169315,0.038247,0.317273,1.873860,0.017836,1.216716
...,...,...,...,...,...,...,...,...,...
2015,(Animation),"(Adventure, IMAX, Children, Comedy)",0.048986,0.001315,0.001205,0.024609,18.712714,0.001141,1.023881
2016,(IMAX),"(Adventure, Children, Animation, Comedy)",0.016767,0.008000,0.001205,0.071895,8.986928,0.001071,1.068845
2017,(Children),"(Adventure, IMAX, Animation, Comedy)",0.063890,0.001315,0.001205,0.018868,14.347484,0.001121,1.017890
2018,(Adventure),"(Comedy, Children, IMAX, Animation)",0.122411,0.001644,0.001205,0.009848,5.990749,0.001004,1.008286
2019,(Comedy),"(Adventure, Children, IMAX, Animation)",0.363288,0.001753,0.001205,0.003318,1.892440,0.000568,1.001570

In [27]:
association_rules(frequent_itemset)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,"(IMAX, Crime)",(Action),0.001205,0.169315,0.001205,1.000000,5.906149,0.001001,inf
1,"(IMAX, Sci-Fi)",(Action),0.006795,0.169315,0.005589,0.822581,4.858284,0.004439,4.682042
2,"(IMAX, Children)",(Animation),0.003178,0.048986,0.002630,0.827586,16.894237,0.002474,5.515879
3,"(Romance, War)",(Drama),0.005918,0.478356,0.004932,0.833333,1.742077,0.002101,3.129863
4,"(Thriller, War)",(Drama),0.004274,0.478356,0.003507,0.820513,1.715276,0.001462,2.906301
5,"(Adventure, IMAX, Sci-Fi)",(Action),0.003397,0.169315,0.003068,0.903226,5.334586,0.002493,8.583744
6,"(Action, Mystery, Crime)",(Thriller),0.003178,0.189479,0.002740,0.862069,4.549670,0.002138,5.876274
7,"(Drama, Mystery, Action)",(Thriller),0.002849,0.189479,0.002521,0.884615,4.668661,0.001981,7.024511
8,"(Thriller, IMAX, Sci-Fi)",(Action),0.002082,0.169315,0.001753,0.842105,4.973599,0.001401,5.261005
9,"(Adventure, IMAX, Children)",(Animation),0.002192,0.048986,0.001753,0.800000,16.331096,0.001646,4.755068
10,"(Adventure, IMAX, Animation)",(Children),0.002082,0.063890,0.001753,0.842105,13.180464,0.001620,5.928694
11,"(Adventure, Musical, Animation)",(Children),0.002740,0.063890,0.002411,0.880000,13.773585,0.002236,7.800913
12,"(Sci-Fi, Animation, Children)",(Adventure),0.002301,0.122411,0.001973,0.857143,7.002174,0.001691,6.143123
13,"(Adventure, IMAX, Comedy)",(Animation),0.001534,0.048986,0.001315,0.857143,17.497603,0.001240,6.657096
14,"(Adventure, IMAX, Comedy)",(Children),0.001534,0.063890,0.001315,0.857143,13.415829,0.001217,6.552767
15,"(Children, IMAX, Comedy)",(Animation),0.001753,0.048986,0.001644,0.937500,19.138003,0.001558,15.216219
16,"(Animation, IMAX, Comedy)",(Children),0.001753,0.063890,0.001644,0.937500,14.673563,0.001532,14.977753
17,"(Musical, Animation, Romance)",(Children),0.001863,0.063890,0.001644,0.882353,13.810413,0.001525,7.956932
18,"(Drama, Mystery, Crime, Action)",(Thriller),0.001534,0.189479,0.001534,1.000000,5.277617,0.001244,inf
19,"(Animation, Children, Fantasy, Comedy)",(Adventure),0.003616,0.122411,0.002959,0.818182,6.683894,0.002516,4.826740
20,"(Adventure, IMAX, Animation, Comedy)",(Children),0.001315,0.063890,0.001205,0.916667,14.347484,0.001121,11.233315
21,"(Adventure, IMAX, Children, Comedy)",(Animation),0.001315,0.048986,0.001205,0.916667,18.712714,0.001141,11.412164

In [26]:
sorted = m1.sort_values(by = ['confidence','lift'], ascending = False)
print(sorted.head())

                              antecedents  consequents  antecedent support  \
204                         (IMAX, Crime)     (Action)            0.001205
1934      (Drama, Mystery, Crime, Action)   (Thriller)            0.001534
1584             (Children, IMAX, Comedy)  (Animation)            0.001753
1586            (Animation, IMAX, Comedy)   (Children)            0.001753
1994  (Adventure, IMAX, Children, Comedy)  (Animation)            0.001315

      consequent support   support  confidence       lift  leverage  \
204             0.169315  0.001205    1.000000   5.906149  0.001001
1934            0.189479  0.001534    1.000000   5.277617  0.001244
1584            0.048986  0.001644    0.937500  19.138003  0.001558
1586            0.063890  0.001644    0.937500  14.673563  0.001532
1994            0.048986  0.001205    0.916667  18.712714  0.001141

      conviction
204          inf
1934         inf
1584   15.216219
1586   14.977753
1994   11.412164

# Clearly, {Crime,IMAX,Action,Drama,Mystery,Thriller,Comedy,Children,Animation,Adventure} is the most associated itemset in this data.